const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');
const { checkAuth } = require('../middlewares/checkAuth');
const multer  = require('multer');
const upload = multer({ dest: 'public/upload/' });

router.get('/', checkAuth,   adminController.index);
router.get('/index', checkAuth,   adminController.index);
router.get('/add-attributes', checkAuth,   adminController.addAttributes);
router.get('/add-new-user', checkAuth,   adminController.addNewUser);
router.get('/add-product', checkAuth,   adminController.addProduct);
router.post('/add-product', upload.single('image'),checkAuth,   adminController.postaddProduct);
router.get('/all-roles', checkAuth,  adminController.allRoles);
router.get('/all-user', checkAuth,   adminController.allUser);
router.get('/attributes', checkAuth,   adminController.attributes);
router.get('/category-list', checkAuth,   adminController.categoryList);
router.get('/cities', checkAuth,   adminController.cities);
router.get('/components', checkAuth,   adminController.components);
router.get('/countries', checkAuth,   adminController.countries);
router.get('/create-role', checkAuth,   adminController.createRole);
router.get('/edit-page', checkAuth,   adminController.editPage);
router.get('/gallery', checkAuth,   adminController.gallery);
router.get('/home-2', checkAuth,   adminController.home2);
router.get('/home-3', checkAuth,   adminController.home3);
router.get('/home-4', checkAuth,   adminController.home4);
router.get('/home-boxed', checkAuth,   adminController.homeBoxed);
router.get('/home-menu-icon-default', checkAuth,   adminController.homeMenuIconDefault);
router.get('/home-menu-icon-hover', checkAuth,   adminController.homeMenuIconHover);
router.get('/list-page', checkAuth,   adminController.listPage);
router.get('/enquiry', checkAuth,   adminController.enquiry);
router.get('/login', checkAuth,   adminController.login);
router.get('/new-category', checkAuth,   adminController.newCategory);
router.post('/postcategory', upload.single('image'),checkAuth,   adminController.postcategory);
router.get('/deletecategory/:id', checkAuth, adminController.deletecategory);
router.get('/new-page', checkAuth,   adminController.newPage);
router.get('/oder-detail', checkAuth,   adminController.oderDetail);
router.get('/oder-list', checkAuth,   adminController.oderList);
router.get('/oder-tracking', checkAuth,   adminController.oderTracking);
router.get('/product-list', checkAuth,   adminController.productList);
router.get('/report', checkAuth,   adminController.report);
router.get('/setting', checkAuth,   adminController.setting);
router.get('/sign-up', checkAuth,   adminController.signUp);
router.get('/states', checkAuth,   adminController.states);

module.exports = router;
