const express = require('express');
const router = express.Router();
const customerController = require('../controllers/customerController');
const { checkAuth } = require('../middlewares/checkAuth');

router.get('/',  checkAuth,   customerController.index);
router.get('/add-attributes', checkAuth,   customerController.addAttributes);
router.get('/add-new-user', checkAuth,   customerController.addNewUser);
router.get('/add-product', checkAuth,   customerController.addProduct);
router.get('/all-roles', checkAuth,   customerController.allRoles);
router.get('/all-user', checkAuth,   customerController.allUser);
router.get('/attributes', checkAuth,   customerController.attributes);
router.get('/category-list', checkAuth,   customerController.categoryList);
router.get('/cities', checkAuth,   customerController.cities);
router.get('/components', checkAuth,   customerController.components);
router.get('/countries', checkAuth,   customerController.countries);
router.get('/create-role', checkAuth,   customerController.createRole);
router.get('/edit-page', checkAuth,   customerController.editPage);
router.get('/gallery', checkAuth,   customerController.gallery);
router.get('/home-2', checkAuth,   customerController.home2);
router.get('/home-3', checkAuth,   customerController.home3);
router.get('/home-4', checkAuth,   customerController.home4);
router.get('/home-boxed', checkAuth,   customerController.homeBoxed);
router.get('/home-menu-icon-default', checkAuth,   customerController.homeMenuIconDefault);
router.get('/home-menu-icon-hover', checkAuth,   customerController.homeMenuIconHover);
router.get('/list-page', checkAuth,   customerController.listPage);
router.get('/login', checkAuth,   customerController.login);
router.get('/new-category', checkAuth,   customerController.newCategory);
router.get('/new-page', checkAuth,   customerController.newPage);
router.get('/oder-detail', checkAuth,   customerController.oderDetail);
router.get('/oder-list', checkAuth,   customerController.oderList);
router.get('/oder-tracking', checkAuth,   customerController.oderTracking);
router.get('/product-list', checkAuth,   customerController.productList);
router.get('/report', checkAuth,   customerController.report);
router.get('/setting', checkAuth,   customerController.setting);
router.get('/sign-up', checkAuth,   customerController.signUp);
router.get('/states', checkAuth,   customerController.states);

module.exports = router;
